language: python
dist: trusty
cache: pip
python:
  - 3.4
  - 3.5
  - 3.6

os:
  - linux

env:
  global:
  - PYTHONUNBUFFERED=yes
  matrix:
  - MATRIX_TOXENV=unit
matrix:
  include:
  - python: '3.6'
    env: TOXENV=flake8
  - python: '3.6'
    env: TOXENV=pydocstyle
before_install:
  - if [[ -v MATRIX_TOXENV ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}-${MATRIX_TOXENV}; fi; env

install:
  - travis_retry pip install -U tox | cat

script:
    - tox -vv
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
